### PR TITLE
fix #6 convert multiple schedules per function

### LINKED ISSUE #6: Converts only the first schedule with timezone for function with multiple schedules
For a function with multiple schedules each with timezone parameter

```yml
events:
  - schedule:
      description: FULL
      rate: cron(0 4 * * ? *)
      timezone: Australia/Melbourne
  - schedule:
      description: PARTIAL
      rate: cron(0/15 0-3 * * ? *)
      timezone: Australia/Melbourne
```
only the first one is converted correctly

### PR DESCRIPTION
**Pull request by gazal-k**
the issue was caused by modifying the events array in place

### CODE REVIEW

**Review by dschep — CHANGES_REQUESTED** [review]
Thanks for the PR!

Could you modify https://github.com/UnitedIncome/serverless-local-schedule/blob/master/test-service/serverless.yml such that this change is necessary?

Thanks 😃

**Comment by gazal-k** [comment]
@dschep is that ok?

**Review by dschep — APPROVED** [review]
Yup. that's perfect. Merging and pushing a new release 😃

**Comment by gazal-k** [comment]
:+1:

**Pull request merged**
