### PR TITLE
Fix rate.match is not a function issue

### LINKED ISSUE #20: TypeError: schedule.rate.match is not a function
Hi, this error started today on my nightly deploy task:

```
Serverless: Converting local crontabs to UTC crontabs...
 
 Type Error ----------------------------------------------
 
  TypeError: schedule.rate.match is not a function
      at ServerlessLocalCrontabs.convertCrontabs (/root/project/build/node_modules/serverless-local-schedule/index.js:73:37)
      at PluginManager.invoke (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:580:20)
      at async PluginManager.spawn (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:602:5)
      at async Object.before:deploy:deploy [as hook] (/root/project/build/node_modules/serverless/lib/plugins/deploy.js:61:11)
      at async PluginManager.invoke (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:580:9)
      at async PluginManager.run (/root/project/build/node_modules/serverless/lib/classes/PluginManager.js:640:7)
      at async Serverless.run (/root/project/build/node_modules/serverless/lib/Serverless.js:457:5)
      at async /root/project/build/node_modules/serverless/scripts/serverless.js:803:9
```

I believe it relates to this bit of configuration in serverless.yml:

```
  subscriptions-f:
    environment: ${file(.env.json)}
    handler: dist/subscriptions-f-handler.handler
    timeout: 900
    events:
      - sns:
          arn: ${file(.env.json):USER_CHAIN_TOPIC}
      - schedule:
          rate: cron(0 * * * ? *)
          timezone: Europe/London
          input:
            topic: 'main'
```

I was able to deploy the same code to UAT and to Production 2 days ago - this issue started on nightly provisioning only.

I don't know if it matters, I have been using serverless-local-schedule for about 1 year but with frameworkVersion < 2.
Now I'm using frameworkVersion: "2"

Any idea? Thank you!

### PR DESCRIPTION
**Pull request by KillDozerX2**
Replaces #21
Fixes #20 
Need this for #13

### CODE REVIEW

**Comment by KillDozerX2** [comment]
@pgrzesik I might have refactored a lot. Let me know if you need some changes.

**Comment by pgrzesik** [comment]
Hey @KillDozerX2 - thanks a lot for the proposed changes - could we keep it a bit more focused though? I believe all the proposed changes are valuable, but I think it would be great to address one problem per PR as we're usually squashing commits into one to keep the consistent formatting. Would that be okay with you to just include the fix that addresses the `rate.match` problem and then submit the rest if needed as separate PRs? Thanks in advance and sorry for inconvenience

**Comment by KillDozerX2** [comment]
@pgrzesik I've put in a lot and I think I got all refactoring done too. I kinda need the type docs for this and I didn't want to be the guy who pushes a single commit. I don't know if I will be able to do what you're asking. I need to have this working soon along with step functiona support for my org to consider contributing and maintaining.

**Comment by pgrzesik** [comment]
Hey @KillDozerX2 - I know you've put a lot of work and that is much appreciated 🙇 Sorry for not being clear upfront, but in our projects we usually follow the approach where PRs should ideally be addressing a single issue - here we have a lot of valuable changes, but would you be able to first submit a PR which just fixes the issue with `rate.match` error and then the other refactorings? Sorry for the inconvenience, but that helps us with maintaining the projects in a bit more structured way

**Comment by KillDozerX2** [comment]
@pgrzesik We're moving towards releasing a fork of this separately as we need it to be immediately available for us to start incorporating it in our services. Once our rush settles down, I will start creating PRs here. Sorry for the inconvenience caused.

**Comment by pgrzesik** [comment]
Thanks a lot @KillDozerX2 - that's totally understandable - we'd be happy to accept contributions whenever you have time 🙇

**Pull request closed without merging**
